<?php
/**
 * ActivityModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationPortal
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Portal API
 *
 * Bumbal Communication API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalCommunicationPortal;

/**
 * ActivityModelTest Class Doc Comment
 *
 * @category    Class */
// * @description ActivityModel
/**
 * @package     BumbalCommunicationPortal
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActivityModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ActivityModel"
     */
    public function testActivityModel()
    {
    }

    /**
     * Test attribute "nr"
     */
    public function testPropertyNr()
    {
    }

    /**
     * Test attribute "activity_type_name"
     */
    public function testPropertyActivityTypeName()
    {
    }

    /**
     * Test attribute "status_name"
     */
    public function testPropertyStatusName()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "date_time_from"
     */
    public function testPropertyDateTimeFrom()
    {
    }

    /**
     * Test attribute "date_time_to"
     */
    public function testPropertyDateTimeTo()
    {
    }

    /**
     * Test attribute "eta_date_time"
     */
    public function testPropertyEtaDateTime()
    {
    }

    /**
     * Test attribute "nr_of_activities"
     */
    public function testPropertyNrOfActivities()
    {
    }

    /**
     * Test attribute "driver_full_name"
     */
    public function testPropertyDriverFullName()
    {
    }

    /**
     * Test attribute "route_status"
     */
    public function testPropertyRouteStatus()
    {
    }

    /**
     * Test attribute "route_latest_position"
     */
    public function testPropertyRouteLatestPosition()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "package_lines"
     */
    public function testPropertyPackageLines()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }
}
