<?php
/**
 * ActivityInfoModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationPortal
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Portal API
 *
 * Bumbal Communication API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalCommunicationPortal;

/**
 * ActivityInfoModelTest Class Doc Comment
 *
 * @category    Class */
// * @description ActivityInfoModel
/**
 * @package     BumbalCommunicationPortal
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActivityInfoModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ActivityInfoModel"
     */
    public function testActivityInfoModel()
    {
    }

    /**
     * Test attribute "instance"
     */
    public function testPropertyInstance()
    {
    }

    /**
     * Test attribute "instance_api_key"
     */
    public function testPropertyInstanceApiKey()
    {
    }

    /**
     * Test attribute "activity_id"
     */
    public function testPropertyActivityId()
    {
    }
}
