<?php
/**
 * AddressModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationPortal
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication API
 *
 * Bumbal Communication Server API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalCommunicationPortal;

/**
 * AddressModelTest Class Doc Comment
 *
 * @category    Class */
// * @description AddressModel
/**
 * @package     BumbalCommunicationPortal
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AddressModel"
     */
    public function testAddressModel()
    {

    }

    /**
     * Test attribute "name_1"
     */
    public function testPropertyName1()
    {

    }

    /**
     * Test attribute "name_2"
     */
    public function testPropertyName2()
    {

    }

    /**
     * Test attribute "street_1"
     */
    public function testPropertyStreet1()
    {

    }

    /**
     * Test attribute "street_2"
     */
    public function testPropertyStreet2()
    {

    }

    /**
     * Test attribute "house_nr"
     */
    public function testPropertyHouseNr()
    {

    }

    /**
     * Test attribute "house_nr_addendum"
     */
    public function testPropertyHouseNrAddendum()
    {

    }

    /**
     * Test attribute "zipcode"
     */
    public function testPropertyZipcode()
    {

    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "iso_country"
     */
    public function testPropertyIsoCountry()
    {

    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {

    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {

    }

}
