<?php
/**
 * ActivityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationPortal
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Portal API
 *
 * Bumbal Communication API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalCommunicationPortal;

use \BumbalCommunicationPortal\Configuration;
use \BumbalCommunicationPortal\ApiClient;
use \BumbalCommunicationPortal\ApiException;
use \BumbalCommunicationPortal\ObjectSerializer;

/**
 * ActivityApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalCommunicationPortal
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ActivityApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for activityRetrieve
     *
     * Retrieve Activity.
     *
     */
    public function testActivityRetrieve()
    {
    }

    /**
     * Test case for validateToken
     *
     * Validate Token.
     *
     */
    public function testValidateToken()
    {
    }
}
